### ISSUE TITLE
Some localized search suggestions showing up

### ISSUE THREAD

**Issue by MicaelJarniac** [dessant/google-us-search-provider#3]
**System**

* OS name: Manjaro KDE (based on Arch Linux)
* OS version: 6.1.31-2-MANJARO (64-bit)
* Browser name: Firefox
* Browser version: 114.0 (64-bit)
* Extension version: 3.0.2

<details>
<summary>About System</summary>

```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.1.31-2-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 82MJ
System Version: IdeaPad Gaming 3 15ACH6
```
</details>

**Bug description**

Some localized search results, likely based on geolocating my IP address, are showing up, despite me using this extension exactly to prevent that.

![samsung](https://github.com/dessant/search-google-us/assets/19514231/e1b0b24c-d6ac-4a02-aef3-faa287ce0b04)
![neigh](https://github.com/dessant/search-google-us/assets/19514231/fbcd4c5c-b504-4378-97db-7d63213eef74)
![fiat](https://github.com/dessant/search-google-us/assets/19514231/aa7ec42c-f28c-4581-b6f6-2230ef06ce06)
![intel](https://github.com/dessant/search-google-us/assets/19514231/c678330b-fefe-4ec2-a90b-6ec59d34f6c8)

**Logs**

Not applicable.

**Comment by dessant** [comment]
I've made some tests, and it seems Google will still return suggestions and some search results that are related to your location, though they appear to be much less relevant and localized than with the default Google search provider.

I'm not aware of a way to prevent this behavior, if someone finds a URL parameter that completely blocks local search results, please share it.
